$kind: http-request
url: "{{baseUrl}}/admin/config"
method: PUT
headers:
  Authorization: Bearer {{accessToken}}
  Content-Type: application/json
body:
  type: json
  content: |-
    {
      "configKey": "DEFAULT",
      "data": {
        "maintenanceMode": false,
        "featureFlags": {
          "newCheckout": true,
          "realtimeNotifications": true
        }
      },
      "status": "ACTIVE"
    }
order: 4000
