const EVENT_VERSION = '1.0.0';

const EVENT_TYPES = Object.freeze({
  PRODUCT_CREATED: 'ProductCreated',
  PRODUCT_UPDATED: 'ProductUpdated',
  PRODUCT_DELETED: 'ProductDeleted',
  PRODUCT_AVAILABILITY_CHANGED: 'ProductAvailabilityChanged',
  CART_ITEM_ADDED: 'CartItemAdded.v1',
  CART_ITEM_UPDATED: 'CartItemUpdated.v1',
  CART_ITEM_REMOVED: 'CartItemRemoved.v1',
  CART_CLEARED: 'CartCleared.v1',
  INVENTORY_UPDATED: 'InventoryUpdated',
  INVENTORY_LOW: 'InventoryLow',
  INVENTORY_OUT_OF_STOCK: 'InventoryOutOfStock',
  ORDER_PLACED: 'OrderPlaced',
  ORDER_CANCELLED: 'OrderCancelled',
  ORDER_ACCEPTED: 'OrderAccepted',
  ORDER_READY: 'OrderReady',
  ORDER_COMPLETED: 'OrderCompleted',
  ORDER_PLACED_V1: 'OrderPlaced.v1',
  ORDER_CANCELLED_V1: 'OrderCancelled.v1',
  ORDER_ACCEPTED_V1: 'OrderAccepted.v1',
  ORDER_READY_V1: 'OrderReady.v1',
  ORDER_COMPLETED_V1: 'OrderCompleted.v1',
  PAYMENT_CREATED: 'PaymentCreated',
  PAYMENT_SUCCESS: 'PaymentSuccess',
  PAYMENT_FAILED: 'PaymentFailed',
  PAYMENT_REFUNDED: 'PaymentRefunded',
  PAYMENT_CREATED_V1: 'PaymentCreated.v1',
  PAYMENT_SUCCESS_V1: 'PaymentSuccess.v1',
  PAYMENT_FAILED_V1: 'PaymentFailed.v1',
  PAYMENT_REFUNDED_V1: 'PaymentRefunded.v1',
  USER_REGISTERED: 'UserRegistered',
  USER_REGISTERED_V1: 'UserRegistered.v1',
  USER_LOGGED_IN_V1: 'UserLoggedIn.v1',
  USER_LOGGED_OUT_V1: 'UserLoggedOut.v1',
  INVENTORY_LOW_V1: 'InventoryLow.v1',
  INVENTORY_OUT_OF_STOCK_V1: 'InventoryOutOfStock.v1',
  NOTIFICATION_CREATED_V1: 'NotificationCreated.v1',
  NOTIFICATION_DELIVERED_V1: 'NotificationDelivered.v1',
  NOTIFICATION_FAILED_V1: 'NotificationFailed.v1',
  ANALYTICS_UPDATED_V1: 'AnalyticsUpdated.v1',
  ADMIN_CONFIG_UPDATED_V1: 'AdminConfigUpdated.v1',
  ADMIN_DASHBOARD_UPDATED_V1: 'AdminDashboardUpdated.v1',
  S3_OBJECT_CREATED: 'S3ObjectCreated',
  IMAGE_PROCESSED: 'ImageProcessed',
  INVOICE_UPLOADED: 'InvoiceUploaded',
  DAILY_ANALYTICS_SCHEDULED: 'DailyAnalyticsScheduled',
  DAILY_REPORT_GENERATED: 'DailyReportGenerated',
  DAILY_REPORT_GENERATED_V1: 'DailyReportGenerated.v1',
  RESTOCK_JOB_QUEUED: 'RestockJobQueued',
});

module.exports = {
  EVENT_VERSION,
  EVENT_TYPES,
};
