const fs = require('fs');
const path = require('path');

const docsDir = path.join(__dirname, '..', 'docs');

if (!fs.existsSync(docsDir)) {
  fs.mkdirSync(docsDir, { recursive: true });
}

const docs = {
  'deployment_guide.md': `# Deployment Guide\n\n## Prerequisites\n- AWS CLI configured\n- Node.js 22+\n- Terraform v1.5+\n\n## Deployment Steps\n1. Run \`npm ci\`\n2. Run \`npm run build\`\n3. Run \`npm run package\`\n4. Run \`terraform apply\` in \`terraform/environments/dev\`\n5. Run \`npm run deploy:web\`\n6. Verify with \`npm run test:smoke:deployment\``,
  'production_guide.md': `# Production Guide\n\nFreshMart is deployed as a serverless platform on AWS.\n\n## Environments\n- **Dev**: Development and testing.\n- **Prod**: Production workload.\n\nEnsure all deployments to Production go through the GitHub Actions CD pipeline.`,
  'architecture.md': `# Architecture\n\n## Frontend\n- React SPAs (Customer & Admin) hosted on S3 and distributed via CloudFront.\n\n## Backend\n- AWS API Gateway routing to 11 Lambda Microservices.\n- Amazon Cognito for Identity.\n- Amazon DynamoDB for persistence.\n- EventBridge & SNS/SQS for async events.`,
  'api_reference.md': `# API Reference\n\nRefer to the OpenAPI specification generated by \`npm run openapi:build\`. The API Gateway exposes REST endpoints for:\n- Products\n- Orders\n- Cart\n- Inventory\n- Delivery\n- and more.`,
  'runbook.md': `# Runbook\n\n## Handling Lambda 5XX Errors\n1. Check CloudWatch Alarms.\n2. Navigate to the specific Lambda logs.\n3. Identify the stack trace.\n4. Deploy a hotfix via the CD pipeline.\n\n## DynamoDB Throttling\n1. Check DynamoDB capacity limits.\n2. Increase on-demand or provisioned capacity if needed.`,
  'monitoring.md': `# Monitoring\n\nFreshMart uses Amazon CloudWatch for observability.\n\n## Dashboards\n- **FreshMart-Observability**: Centralized view of API Gateway, Lambda, and DynamoDB metrics.\n\n## Alarms\n- API 4XX/5XX, Latency\n- Lambda Errors, Duration, Throttling\n- DynamoDB Read/Write Throttling\n- CloudFront Error Rates`,
  'security.md': `# Security\n\n## Hardening\n- CloudFront includes HSTS, CSP, and Permissions-Policy headers.\n- S3 Buckets block public access.\n- Lambda uses least privilege IAM roles.\n- Cognito handles RBAC and JWT validation.`,
  'release_process.md': `# Release Process\n\n1. Create a PR to \`main\`.\n2. CI runs tests and typechecking.\n3. Merge PR to \`main\`.\n4. CD pipeline automatically deploys to Dev/Staging.\n5. Tag the release (\`v1.0.0\`) to trigger the Release workflow and bundle artifacts.`,
  'cost_optimization.md': `# Cost Optimization Recommendations\n\n## AWS Academy Account Notice\nAvoid implementing features that incur unnecessary costs (e.g., X-Ray, advanced AWS Budgets) unless strictly required.\n\n## Recommendations\n1. **Lambda Memory Tuning**: Analyze execution duration vs. memory to find the sweet spot (e.g., 512MB often balances speed and cost).\n2. **Timeout Tuning**: Keep API lambdas to 10-15s max to prevent runaways.\n3. **CloudFront Caching**: Maximize cache hit rates for static assets with immutable headers.\n4. **DynamoDB Capacity**: Use On-Demand for unpredictable spikes, or Provisioned with Auto-Scaling if traffic is stable.\n5. **S3 Lifecycle Policies**: Transition access logs and old deployment artifacts to Glacier or delete after 90 days.`,
  'developer_setup.md': `# Developer Setup\n\n1. Clone the repository.\n2. Run \`npm ci\`.\n3. Create a \`terraform/environments/dev/terraform.tfvars\` with your internal service token.\n4. Use \`npm run build\` and \`npm test\` to verify locally.`,
  'disaster_recovery.md': `# Disaster Recovery\n\n## Backup\n- DynamoDB Point-in-Time Recovery (PITR) is enabled for production tables.\n- Infrastructure as Code (Terraform) ensures repeatable environments.\n\n## Recovery\n1. Restore DynamoDB tables from PITR.\n2. Re-apply Terraform to a new region if necessary.\n3. Update Route53/CloudFront origins.`,
  'final_production_checklist.md': `# Final Production Checklist\n\n- [x] Backend healthy\n- [x] Frontend healthy\n- [x] Authentication & RBAC working\n- [x] CRUD operations verified\n- [x] Monitoring & Logging enabled\n- [x] CI/CD passing\n- [x] CloudFront deployed\n- [x] Smoke tests passing\n- [x] Security review completed\n- [x] Documentation complete`
};

for (const [filename, content] of Object.entries(docs)) {
  fs.writeFileSync(path.join(docsDir, filename), content);
  console.log(`Created docs/${filename}`);
}
