const EVENT_VERSION = '1.0';

const EVENT_TYPES = Object.freeze({
  PRODUCT_CREATED: 'product.created',
  PRODUCT_UPDATED: 'product.updated',
  PRODUCT_DELETED: 'product.deleted',
  PRODUCT_AVAILABILITY_CHANGED: 'product.availability_changed',
  CART_ITEM_ADDED: 'cart.item_added',
  CART_ITEM_UPDATED: 'cart.item_updated',
  CART_ITEM_REMOVED: 'cart.item_removed',
  CART_CLEARED: 'cart.cleared',
  INVENTORY_UPDATED: 'inventory.updated',
  INVENTORY_LOW: 'inventory.low_stock',
  INVENTORY_OUT_OF_STOCK: 'inventory.out_of_stock',
  INVENTORY_RESTOCKED: 'inventory.restocked',
  ORDER_PLACED: 'order.placed',
  ORDER_CANCELLED: 'order.cancelled',
  ORDER_ACCEPTED: 'order.accepted',
  ORDER_READY: 'order.ready',
  ORDER_COMPLETED: 'order.completed',
  PAYMENT_CREATED: 'payment.created',
  PAYMENT_SUCCESS: 'payment.succeeded',
  PAYMENT_FAILED: 'payment.failed',
  PAYMENT_REFUNDED: 'payment.refunded',
  USER_REGISTERED: 'customer.registered',
  USER_LOGGED_IN: 'customer.logged_in',
  USER_LOGGED_OUT: 'customer.logged_out',
  NOTIFICATION_CREATED: 'notification.created',
  NOTIFICATION_DELIVERED: 'notification.delivered',
  NOTIFICATION_FAILED: 'notification.failed',
  ANALYTICS_UPDATED: 'analytics.updated',
  ADMIN_CONFIG_UPDATED: 'admin.config_updated',
  ADMIN_DASHBOARD_UPDATED: 'admin.dashboard_updated',
  S3_OBJECT_CREATED: 's3.object_created',
  IMAGE_PROCESSED: 'image.processed',
  INVOICE_UPLOADED: 'invoice.uploaded',
  DAILY_ANALYTICS_SCHEDULED: 'analytics.daily_scheduled',
  DAILY_REPORT_GENERATED: 'analytics.daily_report_generated',
  RESTOCK_JOB_QUEUED: 'inventory.restock_job_queued',
});

module.exports = {
  EVENT_VERSION,
  EVENT_TYPES,
};
