export const queryKeys = {
  dashboard: ['admin', 'dashboard'],
  products: ['admin', 'products'],
  inventory: ['admin', 'inventory'],
  movements: ['admin', 'inventory', 'movements'],
  forecast: ['admin', 'inventory', 'forecast'],
  suggestions: ['admin', 'inventory', 'suggestions'],
  orders: ['admin', 'orders'],
  customers: ['admin', 'customers'],
  analyticsDashboard: ['admin', 'analytics', 'dashboard'],
  analyticsRevenue: ['admin', 'analytics', 'revenue'],
  analyticsOrders: ['admin', 'analytics', 'orders'],
  analyticsCustomers: ['admin', 'analytics', 'customers'],
  categories: ['admin', 'categories'],
  coupons: ['admin', 'coupons'],
  notifications: ['admin', 'notifications'],
  purchaseOrders: ['admin', 'purchase-orders'],
  reports: ['admin', 'reports'],
  reviews: ['admin', 'reviews'],
  suppliers: ['admin', 'suppliers'],
} as const;
