name: FreshMart Infrastructure CI (Terraform OIDC Plan)

on:
  pull_request:
    branches: [main, develop]
    paths:
      - 'terraform/**'
      - '.github/workflows/ci-terraform.yml'
  push:
    branches: [main, develop]
    paths:
      - 'terraform/**'

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform-plan:
    name: Terraform Format, Validate & OIDC Plan
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment: [dev, qa, prod]
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Configure AWS Credentials via GitHub OIDC (PR Plan Role)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::769044546162:role/freshmart-github-ci-plan-role
          aws-region: ap-southeast-1
          role-session-name: GitHubActions-TerraformPlan-${{ matrix.environment }}

      - name: Terraform Format Check
        run: terraform -chdir=terraform/environments/${{ matrix.environment }} fmt -check

      - name: Terraform Init
        run: terraform -chdir=terraform/environments/${{ matrix.environment }} init

      - name: Terraform Validate
        run: terraform -chdir=terraform/environments/${{ matrix.environment }} validate

      - name: Terraform Plan (Read-Only OIDC)
        id: plan
        run: |
          terraform -chdir=terraform/environments/${{ matrix.environment }} plan -no-color -input=false
        env:
          TF_VAR_internal_service_token: ${{ secrets.TF_VAR_INTERNAL_SERVICE_TOKEN }}
